repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        args: [--style=file]
        files: ^src/.*\.(cpp|c|h|hpp)$

  - repo: local
    hooks:
    - id: cpplint
      name: cpplint
      entry: python3 -m cpplint
      language: system
      args: [--quiet, --filter=-build/include_subdir]
      files: ^src/.*\.(cpp|c|h|hpp)$

    - id: cppcheck
      name: cppcheck
      entry: bash -c 'cppcheck --enable=all --inconclusive --error-exitcode=1 --suppress=missingInclude -I src/gnubgmodule src/gnubgmodule'
      language: system
      files: ^src/.*\.(cpp|c|h|hpp)$
