repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6  # replace with your desired clang-format version
    hooks:
      - id: clang-format
        args: [--style=file]
