[build-system]
requires = [
  "meson>=0.61.5,<0.63.0",
  "meson-python>=0.8.0"
]
build-backend = "meson_python.build"

[project]
name = "gnubg"
version = "1.1"
description = "Python3 bindings for GNU Backgammon neural evaluation"
readme = "README.md"
license = { text = "GPL-2.0-or-later" }
authors = [
    { name = "David Reay", email = "dr323090@falmouth.ac.uk" }
]
dependencies = []
dynamic = ["dependencies"]
