name: Build & test wheels
description: Build and test a Python wheel using cibuildwheel

inputs:
  python:
    required: true
    description: Python ABI tag (PEP 425)
  os:
    required: true
    description: GitHub Actions runner OS

runs:
  using: "composite"
  steps:
    - name: Install system dependencies (Linux)
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          autoconf automake \
          pkg-config \
          python3.12-dev \
          libgtk-3-dev \
          libssl-dev \
          zlib1g-dev

    - name: Install Meson
      if: ${{ inputs.os == 'ubuntu-latest' || inputs.os == 'macos-13' || inputs.os == 'macos-14' }}
      shell: bash
      run: pip install meson ninja cibuildwheel

    - name: Build with meson
      if: ${{ inputs.os == 'ubuntu-latest' || inputs.os == 'macos-13' || inputs.os == 'macos-14' }}
      shell: bash
      run: |
        meson setup build
        meson compile -C build

    - name: Build wheels
      if: ${{ inputs.os == 'ubuntu-latest' || inputs.os == 'macos-13' || inputs.os == 'macos-14' }}
      shell: bash
      env:
        CIBW_SKIP: "pp* *-win32"
        CIBW_BUILD: "${{ inputs.python }}-*"
        CIBW_ARCHS_MACOS: "native"
        CIBW_PLATFORM: ${{ inputs.os == 'ubuntu-latest' && 'linux' || (inputs.os == 'macos-13' && 'macos') || (inputs.os == 'macos-14' && 'macos') || (inputs.os == 'windows-latest' && 'windows') }}
        CIBW_TEST_REQUIRES: "pytest"
        CIBW_TEST_COMMAND: "pytest {project}/tests"
      run: cibuildwheel --output-dir wheelhouse

    - name: Install Meson
      if: ${{ inputs.os == 'windows-latest' }}
      shell: pwsh
      run: pip install meson ninja cibuildwheel

    - name: Build with meson
      if: ${{ inputs.os == 'windows-latest' }}
      shell: pwsh
      run: |
        meson setup build
        meson compile -C build

    - name: Build wheels
      if: ${{ inputs.os == 'windows-latest' }}
      shell: pwsh
      env:
        CIBW_SKIP: "pp* *-win32"
        CIBW_BUILD: "${{ inputs.python }}-*"
        CIBW_ARCHS_MACOS: "native"
        CIBW_PLATFORM: ${{ inputs.os == 'ubuntu-latest' && 'linux' || (inputs.os == 'macos-13' && 'macos') || (inputs.os == 'macos-14' && 'macos') || (inputs.os == 'windows-latest' && 'windows') }}
        CIBW_TEST_REQUIRES: "pytest"
        CIBW_TEST_COMMAND: "pytest {project}/tests"
      run: cibuildwheel --output-dir wheelhouse

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ inputs.os }}-py${{ inputs.python }}
        path: wheelhouse/*.whl
