# .github/workflows/build-wheels.yml
name: Build wheels

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      -
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.os }} / Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
#          - "ubuntu-latest"
#          - "macos-13"
#          - "macos-14"
          - "windows-latest"
        python:
#          - "cp37"
#          - "cp38"
#          - "cp39"
          - "cp310"
#          - "cp311"
#          - "cp312"
#          - "cp313"
        exclude:
          - os: "macos-14"
            python: "cp37"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autoconf automake \
            pkg-config \
            python3.12-dev \
            libgtk-3-dev \
            libssl-dev \
            zlib1g-dev

      - name: Install Meson
        run: pip install meson ninja cibuildwheel

      - name: Build with meson
        run: |
          meson setup build
          meson compile -C build

      - name: Build wheels (linux, macOS, Windows)
        env:
          CIBW_SKIP: "pp* *-win32"
          CIBW_BUILD: "${{ matrix.python }}-*"
          CIBW_ARCHS_MACOS: "native"
          CIBW_PLATFORM: ${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'macos-13' && 'macos') || (matrix.os == 'macos-14' && 'macos') ||(matrix.os == 'windows-latest' && 'windows')}}
          CIBW_TEST_REQUIRES: "pytest"
#          CIBW_TEST_COMMAND: "pytest {project}/tests"
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-py${{ matrix.python }}
          path: wheelhouse/*.whl
