name: C/C++ Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read    # for checkout

jobs:
  lint-cpp:
    name: Lint C/C++ code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-format \
            cppcheck \
            python3-pip \
            python3-dev
          
          pip3 install cpplint

      - name: Run cppcheck static analysis
        run: |
          cppcheck \
<<<<<<< Updated upstream
          --enable=all \
          --inconclusive \
          --error-exitcode=1 \
          --suppress=missingIncludeSystem \
          -I gnubg-nn/ \
          -I gnubg-nn/gnubg \
          -I gnubg-nn/gnubg/lib \
          -I gnubg-nn/analyze \
          -I gnubg-nn/py \
          src/
=======
            --enable=all \
            --inconclusive \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            -I src/ \
            src/
>>>>>>> Stashed changes

      - name: Verify formatting with clang-format
        run: |
          find src/ -regex '.*\.\(c\|cpp\|h\|hpp\)' -print0 \
            | xargs -0 clang-format --dry-run --Werror

      - name: Run cpplint style checks
        run: |
          find src/ -regex '.*\.\(c\|cpp\|h\|hpp\)' -print0 \
            | xargs -0 cpplint --quiet
