name: C/C++ Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-cpp:
    name: Lint C/C++ code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-format \
            cppcheck \
            python3-pip \
            python3-dev
          
          pip3 install cpplint

      - name: Run cppcheck static analysis (matches pre-commit)
        run: |
          cppcheck \
            --enable=all \
            --inconclusive \
            --error-exitcode=1 \
            --suppress=missingInclude \
            --suppress=missingIncludeSystem \
            -I src/gnubgmodule src/gnubgmodule

      - name: Verify formatting with clang-format (matches pre-commit)
        run: |
          find src/gnubgmodule/ -regex '.*\.\(c\|cpp\|h\|hpp\)' -print0 \
            | xargs -0 clang-format --dry-run --Werror --style=file

      - name: Run cpplint style checks (matches pre-commit)
        run: |
          find src/gnubgmodule/ -regex '.*\.\(c\|cpp\|h\|hpp\)' -print0 \
            | xargs -0 python3 -m cpplint \
              --quiet \
              --filter=-build/include_subdir
