name: Publish wheels

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
  push:
    tags:
      - 'v*'   # trigger on version tags like v1.0.0

permissions:
  contents: write  # required for release upload
  id-token: write  # required for OIDC (optional)

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - name: Set release tag
        id: vars
        run: |
          echo "tag=${{ github.event.inputs.tag || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: manylinux-wheels
          path: dist/

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: macos-wheels
          path: dist/

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: windows-wheels-mingw
          path: dist/

      - name: Install Twine
        run: pip install --upgrade pip twine

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: twine upload --repository testpypi dist/*.whl

      - name: Create GitHub release (if needed)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          files: dist/*.whl
          generate_release_notes: true
