name: Publish wheels

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: manylinux-wheels
          path: dist/

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: macos-wheels
          path: dist/

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: windows-wheels-mingw
          path: dist/

      - name: Install Twine
        run: pip install --upgrade pip twine

      - name: Check contents
        run: ls -lh dist

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: twine upload --repository testpypi dist/*.whl
