name: Release to PyPI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose pypi environment to publish to"
        required: true
        default: "testpypi"
        type: choice
        options:
          - "testpypi"
          - "pypi"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-13"
          - "macos-14"
          - "windows-latest"
        python:
          - "cp37"
          - "cp38"
          - "cp39"
          - "cp310"
          - "cp311"
          - "cp312"
          - "cp313"
        exclude:
          - os: "macos-14"
            python: "cp37"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./.github/actions/build-wheel
        with:
          python: ${{ matrix.python }}
          os: ${{ matrix.os }}

      - name: Install Twine
        run: pip install --upgrade pip twine

      - name: Upload to PyPI or TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --repository ${{ inputs.environment }} wheelhouse/*.whl
