name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # fetch all submodules (use `true` for one level, or 'recursive' for nested)
          submodules: recursive
          # if you need the full commit history in both superrepo and submodules
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autoconf automake \
            pkg-config \
            python3-dev \
            libgtk-3-dev \
            libssl-dev \
            zlib1g-dev

      - name: Apply Patch files
        run: make patch

      - name: Generate configure script & configure
        run: make configure

      - name: Set up Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version-file: .python-version

      - name: Install Python dependencies
        run: make install

      - name: Build Python extension
        run: make build

      - name: Run test suite
        run: make test
